version: "3.9"
services:
  db:
    image: "redis/redis-stack-server"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 256mb
    volumes:
      - dbv:/data
  backend:
    environment:
      - REDIS_CONNECTION_URL=redis://db:6379
    build: backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 256mb
  frontend:
    build: frontend
    depends_on:
      - backend
    ports:
      - "80:3000"
    deploy:
      resources:
        limits:
          memory: 256mb
volumes:
  dbv:
